version: "3.9"
services:
  frontend:
    image: typing-frontend
    ports:
      - "3000:3000"
    volumes:
      - /Users/josephhu/coding/projects/typing/frontend:/app
    build: ./frontend
  backend:
    image: typing-backend
    volumes:
      - /Users/josephhu/coding/projects/typing/backend:/go/src/hujoseph99/typing
    build: ./backend

