version: "3.9"
services:
  frontend:
    image: typing-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    build: ./frontend
  backend:
    image: typing-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/src/hujoseph99/typing
    build: ./backend

