export const GET_RACE = "GET_RACE";
export const GET_RACE_SUCCESS = "GET_RACE_SUCCESS";
export const GET_RACE_FAILURE = "GET_RACE_FAILURE";
export const INPUT_CORRECT = "INPUT_CORRECT";
export const INPUT_INCORRECT = "INPUT_INCORRECT";
export const INPUT_FINISHED_WORD = "INPUT_FINISHED_WORD";
